### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Avangion101** [asmith1979/lxf286_3DWorld#1]
There seems to be a missing file called worldmanager.py

**Comment by asmith1979** [comment]
Thank you for letting me know, it's there now, apologies.

**Comment by Avangion101** [comment]
The worldManager.py file seems to be a html document file rather than a python module.

**Comment by asmith1979** [comment]
Apologies, try now.

**Comment by Avangion101** [comment]
Perfect that now works, thanks for that.
